name:               openmapper-desktop
# just for humans, typically '1.2+git' or '1.3.2'
version:            '0.1.11'
# 79 char long summary
summary:            Mapping App
description:        |
  OpenMapper can be used to map various things, from a room to a whole flat.  More information can be found here -> https://github.com/OpenMapper/OpenMapperDesktop
# must be 'stable' to release into candidate/stable channels
grade:              stable
# use 'strict' once you have the right plugs and slots
confinement:        classic
icon:               snap/gui/icon.png
type:               app
apps:
  openmapper:
    command:        desktop-launch ${SNAP}/openmapper/OpenMapperDesktop
    plugs:          [home, unity7, x11, camera, opengl]
architectures:      [amd64]

parts:
# part name can take whatever identifier one likes.
  openmapper:
    source-type:    git
    plugin:         cmake
    configflags:
      - -DCREATE_SNAP_APP=ON
    # A list of Ubuntu packages to be installed on the host to aid in building the part. These packages will not go into the final snap.
    after:          [desktop-qt5]
    build-packages:
      - libeigen3-dev
      - build-essential
      - libopencv-dev
      - freeglut3-dev # OpenGL
      - qt5-default
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5opengl5
      - libqt5opengl5-dev
      - libgl1
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libstdc++6
      - libqt5dbus5
      - libopencv-calib3d-dev
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
    # A set of Ubuntu packages to be downloaded and unpacked to join the part before it’s built. Note that these packages are not installed on the host. Like the rest of the part, all files from these packages will make it into the final snap unless filtered out via the prime keyword.
    # stage-packages:
